"""生成 notebooks/ 下的 4 个学习 notebook。

每个 notebook 是一个 .ipynb JSON 文件,包含 markdown + code cell。
执行 ``python scripts/generate_notebooks.py`` 重新生成。
"""
from __future__ import annotations

import json
from pathlib import Path

NBFORMAT = 4
NBFORMAT_MINOR = 5

NOTEBOOKS_DIR = Path(__file__).resolve().parent.parent / "notebooks"
NOTEBOOKS_DIR.mkdir(exist_ok=True)


def _md(*lines: str) -> dict:
    """构造一个 markdown cell。"""
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": list(lines),
    }


def _code(*lines: str) -> dict:
    """构造一个 code cell,outputs/execution_count 留空。"""
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": list(lines),
    }


def _nb(cells: list[dict]) -> dict:
    """构造一个 .ipynb 文件结构。"""
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.11"},
        },
        "nbformat": NBFORMAT,
        "nbformat_minor": NBFORMAT_MINOR,
    }


def nb_01_single_agent() -> None:
    cells = [
        _md(
            "# 01 - 最小可运行的 CrewAI\n",
            "\n",
            "本 notebook 演示 CrewAI 的最小工作单元:\n",
            "\n",
            "- 1 个 **Tool**(可调用的 Python 函数)\n",
            "- 1 个 **Agent**(LLM + tools + 角色定义)\n",
            "- 1 个 **Task**(给 agent 的指令)\n",
            "- 1 个 **Crew**(把 agent 和 task 装到一起)\n",
            "- `crew.kickoff()` 跑一次\n",
            "\n",
            "跑完这个 notebook,你就能理解生产代码中 8 代理 `AnalysisCrew`\n",
            "的每一层在做什么。\n",
            "\n",
            "**前置条件**:`.env` 中设置了 `MINIMAX_API_KEY` 和 `LITELLM_MODEL`。\n",
            "本 notebook 每次 LLM 调用大约 2-5 秒,总共 1-3 次调用。\n",
        ),
        _code(
            "from alphaquant.infrastructure.config import get_settings\n",
            "from alphaquant.infrastructure.llm import get_llm\n",
            "\n",
            "settings = get_settings()\n",
            "print(f\"Model: {settings.litellm_model}\")\n",
            "llm = get_llm(temperature=0.1)\n",
            "print(\"LLM ready\")\n",
        ),
        _code(
            "from crewai.tools import tool\n",
            "\n",
            "@tool(\"echo\")\n",
            "def echo_tool(text: str) -> str:\n",
            '    """回显输入文本。用于演示 tool 调用。"""\n',
            '    return f"echo: {text}"\n',
            "\n",
            "# tool 本身就是一个可调用的对象,可以直接 run\n",
            'print(echo_tool.run(text="hello"))\n',
        ),
        _code(
            "from crewai import Agent\n",
            "\n",
            "agent = Agent(\n",
            '    role="回声员",\n',
            '    goal="把用户输入回显出来",\n',
            '    backstory="你是一个简单的回声员,负责把用户的输入原样返回。",\n',
            "    tools=[echo_tool],\n",
            "    llm=llm,\n",
            "    verbose=False,  # 关闭 verbose,这里用 notebook 自己的 cell 观察\n",
            ")\n",
            'print(f"Agent: {agent.role}")\n',
        ),
        _code(
            "from crewai import Task\n",
            "\n",
            "task = Task(\n",
            '    description="用 echo 工具回显文本 \'Hello, CrewAI!\'",\n',
            '    expected_output="回显后的文本",\n',
            "    agent=agent,\n",
            ")\n",
            'print(f"Task assigned to: {task.agent.role}")\n',
        ),
        _code(
            "from crewai import Crew, Process\n",
            "\n",
            "crew = Crew(\n",
            "    agents=[agent],\n",
            "    tasks=[task],\n",
            "    process=Process.sequential,\n",
            "    verbose=True,  # 这里打开 verbose 看到内部步骤\n",
            ")\n",
            "result = crew.kickoff(inputs={})\n",
            'print("---")\n',
            'print("Result type:", type(result).__name__)\n',
            'print("Result.raw:")\n',
            "print(result.raw)\n",
        ),
        _md(
            "## 你刚才看到了什么\n",
            "\n",
            "1. `crew.kickoff(inputs={})` 启动 crew\n",
            "2. 因为 `process=sequential`,只有一个 task,manager 没有委托,agent 直接拿到 task\n",
            "3. Agent 决定调用 echo 工具,传 `'Hello, CrewAI!'`\n",
            "4. Tool 返回 `'echo: Hello, CrewAI!'`\n",
            "5. Agent 把工具结果作为最终输出\n",
            "6. `CrewOutput` 对象包含 `.raw`(原始文本)、`.tasks_output`(每个 task 的输出)等\n",
            "\n",
            "## 跟生产代码的对应关系\n",
            "\n",
            "| 教学示例 | AnalysisCrew 中的位置 |\n",
            "|---|---|\n",
            "| `echo_tool` | `tools/company_lookup_tool.py` 等 5 个真实工具 |\n",
            "| 回声员 | `agents/company_resolver.py` 等 8 个真实 agent |\n",
            "| 1 个 task | `_TASK_TEMPLATES` 中 8 个真实 task |\n",
            "| `Crew(...)` | `AnalysisCrew.crew = self._build_crew()` |\n",
            "| `kickoff()` | `AnalysisCrew.kickoff()` → `Flow.run()` |\n",
        ),
    ]
    (NOTEBOOKS_DIR / "01_single_agent.ipynb").write_text(
        json.dumps(_nb(cells), ensure_ascii=False, indent=1),
        encoding="utf-8",
    )


def nb_02_crew_basics() -> None:
    cells = [
        _md(
            "# 02 - Sequential vs Hierarchical\n",
            "\n",
            "CrewAI 有 3 种 process 模式:\n",
            "\n",
            "- **sequential**:task 按列表顺序串行执行,前一个的输出自动成为后一个的 context\n",
            "- **hierarchical**:增加一个 manager agent,manager 决定委托哪些 agent 做哪些 task\n",
            "- consensualic(已废弃)\n",
            "\n",
            "本 notebook 用同一个 2-agent + 2-task 的结构,对比 sequential 和\n",
            "hierarchical 的输出差异。\n",
        ),
        _code(
            "from alphaquant.infrastructure.llm import get_llm\n",
            "from crewai import Agent, Task, Crew, Process\n",
            "\n",
            "llm = get_llm(temperature=0.1)\n",
        ),
        _code(
            "researcher = Agent(\n",
            '    role="研究员",\n',
            '    goal="收集信息",\n',
            '    backstory="你负责收集关于主题的事实信息。",\n',
            "    tools=[],\n",
            "    llm=llm,\n",
            ")\n",
            "writer = Agent(\n",
            '    role="写作者",\n',
            '    goal="把研究结果写成一句简短的中文总结",\n',
            '    backstory="你负责把研究发现凝练成一句话。",\n',
            "    tools=[],\n",
            "    llm=llm,\n",
            ")\n",
        ),
        _code(
            "research_task = Task(\n",
            '    description="研究主题 \'CrewAI 框架\',列出 3 个关键事实。",\n',
            '    expected_output="3 个关键事实的列表",\n',
            "    agent=researcher,\n",
            ")\n",
            "write_task = Task(\n",
            '    description="把研究发现写成一句简短的中文总结。",\n',
            '    expected_output="一句中文总结",\n',
            "    agent=writer,\n",
            "# sequential 模式下,前一个 task 的输出自动成为后一个 task 的 context,\n",
            "# 所以 write_task 写描述时不用显式引用 research_task。\n",
            ")\n",
        ),
        _code(
            "seq_crew = Crew(\n",
            "    agents=[researcher, writer],\n",
            "    tasks=[research_task, write_task],\n",
            "    process=Process.sequential,\n",
            "    verbose=False,\n",
            ")\n",
            "seq_result = seq_crew.kickoff(inputs={})\n",
            'print("=== Sequential Result ===")\n',
            'print("Research task output:")\n',
            "print(seq_result.tasks_output[0].raw[:300])\n",
            "print()\n",
            'print("Write task output:")\n',
            "print(seq_result.tasks_output[1].raw)\n",
        ),
        _code(
            "hier_crew = Crew(\n",
            "    agents=[researcher, writer],\n",
            "    tasks=[research_task, write_task],\n",
            "    process=Process.hierarchical,\n",
            "    manager_llm=llm,  # hierarchical 模式必须指定 manager_llm\n",
            "    verbose=False,\n",
            ")\n",
            "hier_result = hier_crew.kickoff(inputs={})\n",
            'print("=== Hierarchical Result ===")\n',
            'print("Final output:")\n',
            "print(hier_result.raw)\n",
        ),
        _md(
            "## 你看到的区别\n",
            "\n",
            "**Sequential**:\n",
            "\n",
            "- task 0 (research) 先跑,完整结果传给 task 1 (write)\n",
            "- 你可以访问 `result.tasks_output[0]` 和 `result.tasks_output[1]` 看每一步\n",
            "- 没有 manager,完全按列表顺序\n",
            "\n",
            "**Hierarchical**:\n",
            "\n",
            "- manager LLM 决定:这个 task 派给谁?什么时候开始?\n",
            "- 你只能拿到最终 `result.raw`,中间的 task 分配对用户不可见\n",
            "- manager 增加了 1 次额外的 LLM 调用(管理决策)\n",
            "- 适合:task 之间依赖关系不明确、需要动态调整的场景\n",
            "\n",
            "## 跟生产代码的对应\n",
            "\n",
            "AlphaQuant 的 `AnalysisCrew` 用 `Process.hierarchical`,因为 8 个 task 之间的\n",
            "依赖是隐式的(数据收集 → 分析 → 写报告),manager 能更好地协调。\n",
            "在 `crews/analysis_crew.py` 的 `_build_crew()` 里可以看到具体配置。\n",
        ),
    ]
    (NOTEBOOKS_DIR / "02_crew_basics.ipynb").write_text(
        json.dumps(_nb(cells), ensure_ascii=False, indent=1),
        encoding="utf-8",
    )


def nb_03_crew_events() -> None:
    cells = [
        _md(
            "# 03 - 订阅 crewai_event_bus\n",
            "\n",
            "CrewAI 0.20+ 把所有执行事件发布到 `crewai_event_bus` 上。你可以在\n",
            "不修改 crew 内部代码的情况下,订阅这些事件来观察 / 记录 / 触发副作用。\n",
            "\n",
            "常见事件类型:\n",
            "\n",
            "- `CrewKickoffStarted` / `CrewKickoffCompleted`\n",
            "- `TaskStarted` / `TaskCompleted` / `TaskFailed`\n",
            "- `AgentExecutionStarted` / `AgentExecutionCompleted`\n",
            "- `ToolUsageStarted` / `ToolUsageFinished`\n",
            "- `LLMCallStarted` / `LLMCallCompleted`\n",
        ),
        _code(
            "from crewai.events import (\n",
            "    crewai_event_bus,\n",
            "    TaskStartedEvent,\n",
            "    TaskCompletedEvent,\n",
            "    ToolUsageStartedEvent,\n",
            "    ToolUsageFinishedEvent,\n",
            ")\n",
            "\n",
            "def on_task_start(source, event):\n",
            '    desc = getattr(event, "context", "") or ""\n',
            '    print(f"  ▶ TASK START: {desc[:80]}")\n',
            "\n",
            "def on_task_done(source, event):\n",
            '    print("  ✓ TASK DONE")\n',
            "\n",
            "def on_tool_start(source, event):\n",
            '    print(f"    ↪ TOOL: {event.agent_role} → {event.tool_name} args={event.tool_args}")\n',
            "\n",
            "def on_tool_done(source, event):\n",
            '    print(f"    ✓ TOOL DONE: {event.tool_name}")\n',
            "\n",
            "# crewai_event_bus.on(EventType)(handler) 返回装饰器,\n",
            "# 但直接调用也可以注册 handler。\n",
            "crewai_event_bus.on(TaskStartedEvent)(on_task_start)\n",
            "crewai_event_bus.on(TaskCompletedEvent)(on_task_done)\n",
            "crewai_event_bus.on(ToolUsageStartedEvent)(on_tool_start)\n",
            "crewai_event_bus.on(ToolUsageFinishedEvent)(on_tool_done)\n",
            'print("事件订阅已安装")\n',
        ),
        _code(
            "from alphaquant.infrastructure.llm import get_llm\n",
            "from crewai import Agent, Task, Crew, Process\n",
            "from crewai.tools import tool\n",
            "\n",
            "@tool(\"reverse\")\n",
            "def reverse_tool(text: str) -> str:\n",
            '    """反转字符串。"""\n',
            "    return text[::-1]\n",
            "\n",
            "llm = get_llm(temperature=0.1)\n",
            "agent = Agent(\n",
            '    role="反转员",\n',
            '    goal="反转用户输入",\n',
            '    backstory="用 reverse 工具反转字符串。",\n',
            "    tools=[reverse_tool],\n",
            "    llm=llm,\n",
            "    verbose=False,\n",
            ")\n",
            "task = Task(\n",
            '    description="反转字符串 \'CrewAI\'",\n',
            '    expected_output="反转后的字符串",\n',
            "    agent=agent,\n",
            ")\n",
            "crew = Crew(\n",
            "    agents=[agent],\n",
            "    tasks=[task],\n",
            "    process=Process.sequential,\n",
            "    verbose=False,\n",
            ")\n",
            'print("Crew ready")\n',
        ),
        _code(
            'print("=== Kickoff ===")\n',
            "result = crew.kickoff(inputs={})\n",
            'print("=== Done ===")\n',
            'print(f"Final: {result.raw}")\n',
        ),
        _md(
            "## 这就是 `infrastructure/crew_events.py` 在做的事\n",
            "\n",
            "那个文件实现了:\n",
            "\n",
            "- `CrewEventBridge`:一个线程安全的事件订阅器,把事件存到 deque\n",
            "- `CrewEventSnapshot`:UI 读取的不可变快照\n",
            "- `format_event_line`:把事件格式化成人类可读的单行\n",
            "\n",
            "Streamlit `1_Analyze.py` 页面用它来:\n",
            "\n",
            "1. 在 status 块内显示\"当前正在运行 agent X 调用 tool Y\"\n",
            "2. 在 `asyncio.run` 完成后,在折叠块里 dump 整个事件时间线\n",
            "\n",
            "你可以把这里的 `print` 换成 `logging.info` 或 `bridge._append()`,\n",
            "就构成了生产代码的 `CrewEventBridge` 雏形。\n",
        ),
    ]
    (NOTEBOOKS_DIR / "03_crew_events.ipynb").write_text(
        json.dumps(_nb(cells), ensure_ascii=False, indent=1),
        encoding="utf-8",
    )


def nb_04_async_tasks() -> None:
    cells = [
        _md(
            "# 04 - async_execution 加速\n",
            "\n",
            "如果某些 task 之间没有依赖,可以并行跑。\n",
            "CrewAI 用 `Task(async_execution=True)` 标记,让 manager 调度时并行启动。\n",
            "\n",
            "本 notebook 跑 3 个独立 task(3 种语言的问候),对比:\n",
            "\n",
            "- 全部 sequential\n",
            "- 全部 `async_execution=True`\n",
            "\n",
            "总耗时差异会很明显(几乎 3 倍)。\n",
            "\n",
            "**注意**:本 notebook 会发 6 次 LLM 调用,合计约 30-60 秒。\n",
        ),
        _code(
            "import time\n",
            "from alphaquant.infrastructure.llm import get_llm\n",
            "from crewai import Agent, Task, Crew, Process\n",
            "\n",
            "llm = get_llm(temperature=0.1)\n",
            "\n",
            "spanish_agent = Agent(\n",
            '    role="西语翻译",\n',
            '    goal="用西语问候",\n',
            '    backstory="你用西语说你好。",\n',
            "    tools=[],\n",
            "    llm=llm,\n",
            ")\n",
            "french_agent = Agent(\n",
            '    role="法语翻译",\n',
            '    goal="用法语问候",\n',
            '    backstory="你用法语说你好。",\n',
            "    tools=[],\n",
            "    llm=llm,\n",
            ")\n",
            "japanese_agent = Agent(\n",
            '    role="日语翻译",\n',
            '    goal="用日语问候",\n',
            '    backstory="你用日语说你好。",\n',
            "    tools=[],\n",
            "    llm=llm,\n",
            ")\n",
        ),
        _code(
            "seq_tasks = [\n",
            '    Task(description="用西语说\'你好\'", expected_output="一个西语问候", agent=spanish_agent),\n',
            '    Task(description="用法语说\'你好\'", expected_output="一个法语问候", agent=french_agent),\n',
            '    Task(description="用日语说\'你好\'", expected_output="一个日语问候", agent=japanese_agent),\n',
            "]\n",
            "seq_crew = Crew(\n",
            "    agents=[spanish_agent, french_agent, japanese_agent],\n",
            "    tasks=seq_tasks,\n",
            "    process=Process.sequential,\n",
            "    verbose=False,\n",
            ")\n",
            "\n",
            "t0 = time.time()\n",
            "seq_crew.kickoff(inputs={})\n",
            "seq_t = time.time() - t0\n",
            'print(f"Sequential 总耗时: {seq_t:.2f}s")\n',
        ),
        _code(
            "async_tasks = [\n",
            '    Task(description="用西语说\'你好\'", expected_output="一个西语问候", agent=spanish_agent, async_execution=True),\n',
            '    Task(description="用法语说\'你好\'", expected_output="一个法语问候", agent=french_agent, async_execution=True),\n',
            '    Task(description="用日语说\'你好\'", expected_output="一个日语问候", agent=japanese_agent, async_execution=True),\n',
            "]\n",
            "async_crew = Crew(\n",
            "    agents=[spanish_agent, french_agent, japanese_agent],\n",
            "    tasks=async_tasks,\n",
            "    process=Process.sequential,  # process 仍然是 sequential,只是 task 自己标了 async\n",
            "    verbose=False,\n",
            ")\n",
            "\n",
            "t0 = time.time()\n",
            "async_crew.kickoff(inputs={})\n",
            "async_t = time.time() - t0\n",
            'print(f"Async 总耗时: {async_t:.2f}s")\n',
            'print(f"加速比: {seq_t / async_t:.2f}x")\n',
        ),
        _md(
            "## 跟生产代码的对应\n",
            "\n",
            "`AnalysisCrew` 用 `_ASYNC_TASK_INDICES = {0, 1, 2, 3, 4, 5, 6}`,\n",
            "意思是前 7 个 task(数据 0-3 + 分析 4-6)并行跑,只有 idx 7 (`report_writer`)\n",
            "是串行的 —— 因为它需要消费前 3 个分析 task 的输出。\n",
            "\n",
            "在 `crews/analysis_crew.py` 的 `_build_tasks()` 中:\n",
            "\n",
            "```python\n",
            "async_execution=idx in self._ASYNC_TASK_INDICES,\n",
            "```\n",
            "\n",
            "如果你想让 `report_writer` 也并行,会出现两个问题:\n",
            "\n",
            "1. 它需要 `tasks[4]`、`tasks[5]`、`tasks[6]` 的输出作为 context,显式注入可以解决\n",
            "2. 但如果数据 task 还没跑完,manager 调度时可能会和它们抢资源,反而变慢\n",
            "\n",
            "`_ASYNC_TASK_INDICES` 的设计原则:\n",
            "\n",
            "- 没有数据依赖的 task 标 async\n",
            "- 报告写作者必须最后跑(用 `context=[tasks[4], tasks[5], tasks[6]]` 显式注入)\n",
            "- 显式控制并行边界,比全部 async 更稳定\n",
        ),
    ]
    (NOTEBOOKS_DIR / "04_async_tasks.ipynb").write_text(
        json.dumps(_nb(cells), ensure_ascii=False, indent=1),
        encoding="utf-8",
    )


if __name__ == "__main__":
    nb_01_single_agent()
    nb_02_crew_basics()
    nb_03_crew_events()
    nb_04_async_tasks()
    print(f"Generated 4 notebooks in {NOTEBOOKS_DIR}")
